### ISSUE TITLE
 The name 'SteamVR_Actions' does not exist in the current context

### ISSUE THREAD

**Issue by Shizola** [charles-river-analytics/VSDK-Unity#11]
Created a new project, import SteamVR from asset store.

Import Virtuoso package, then get error 
- 

Assets\VIRTUOSO\Scripts\HapticSDK\Haptic Devices\ViveDevice.cs(85,33): error CS0103: The name 'SteamVR_Actions' does not exist in the current context

also, the scene in the examples packages is missing materials and prefabs.

**Comment by ddugganCRA** [comment]
Thanks for catching this @Shizola. It looks like a few lines in ViveDevice.cs are missing directives to prevent issues prior to you generating the SteamVR Input files.

If you are able to generate the SteamVR input files (see the wiki if unsure what I mean) then it should all compile OK, but if not I will have a hotfix available later today as this should be a straightforward fix.

Could you clarify what you mean by the examples packages? In the VSDK project or in the tutorial files?

**Comment by ddugganCRA** [comment]
Resolved via #12 

If issues persist with sample files, please open an additional issue.
