### ISSUE TITLE
Support Native Unity XR API

### ISSUE THREAD

**Issue by andybak** [charles-river-analytics/VSDK-Unity#3]
It would be quite nice to avoid bringing in the huge SteamVR or Oculus SDKs for situations where the extra functionality is not needed. VRTK 4.x works via the native Unity XR API. Is there a chance VSDK could also?

**Comment by ddugganCRA** [comment]
Hey @andybak, that is definitely something we can do. 

We have some small changes from VRTK, one of which is that we treat trackers as separate objects than controllers, so I believe I'd just need to implement a tracker SDK for Unity XR and it should work. I'll try to look into that this week.

**Comment by ddugganCRA** [comment]
Took longer than expected, but has been added. The largest hold up was that I wanted to provide the best support I could for the new 2019.1+ XR input features added by Unity. UnityXR support for VSDK will come to mainstream on v1.01, releasing sometime this week.
